site_name: AI Challenge 2025
site_url: https://automotiveaichallenge.github.io/aichallenge-documentation-2025/
repo_url: https://github.com/AutomotiveAIChallenge/aichallenge-documentation-2025
docs_dir: docs
copyright: "&copy; 2025 TIER IV, Inc."
use_directory_urls: false

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - announce.dismiss
  palette:
    scheme: slate
    primary: custom
    accent: purple
    # logo:
    # favicon:

nav:
  - index: index.md
  - getting-started.md
  - preliminaries:
      - preliminaries/rules.md
      - preliminaries/submission.md
      - preliminaries/check-results.md
  - finals:
      - finals/index.md
      - finals/operation.md
      - finals/agreement.md
  - setup:
      - setup/requirements.md
      - setup/workspace-setup.md
      - setup/docker.md
      - setup/headless-simulation.md
      - setup/visible-simulation.md
      - setup/build-docker.md
  - development:
      - development/workspace-usage.md
      - development/main-module.md
      - development/reference.md
  - specifications:
      - specifications/interface.md
      - specifications/hardware.md
      - specifications/simulator.md
  - course:
      - course/index.md
      - course/vehicle.md
      - course/velocity_planning.md
      - course/avoidance.md
  - FAQ: faq.md
  - Community: community.md

extra_css:
  - stylesheets/custom.css

markdown_extensions:
  - admonition
  - attr_list

plugins:
  - search:
  - i18n:
      docs_structure: suffix
      languages:
        - locale: ja
          default: true
          name: 日本語
          build: true
          nav_translations:
            index: 大会概要
            preliminaries: 予選
            finals: 決勝
            setup: 環境構築
            development: 開発
            specifications: 仕様
            course: 入門講座
            Community: コミュニティ
        - locale: en
          name: English
          build: true
          nav_translations:
            index: Top Page
            preliminaries: Preliminaries
            setup: Setup
            development: Development
            specifications: Specifications
            course: Course
